#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# get the directories in order
mkdir -p /etc/portage/profile
mkdir -p /etc/portage/package.accept_keywords
if [[ -f /etc/portage/package.keywords ]]; then
    mv /etc/portage/package.keywords /etc/portage/package.accept_keywords/prebuilt-1
fi
mkdir -p /etc/portage/package.mask
mkdir -p /etc/portage/package.unmask
mkdir -p /etc/portage/package.use

# needed in order to install pip packages as root
echo 'dev-python/pip vanilla' >> /etc/portage/package.use/pip
# needed to create disk images
echo 'sys-fs/lvm2 -thin' >> /etc/portage/package.use/grub
echo 'sys-boot/grub device-mapper' >> /etc/portage/package.use/grub
echo 'sys-boot/grub grub_platforms_efi-64' >> /etc/portage/package.use/grub  # always enable efi-64
if [[ 'amd64' == "${ARCH}" ]]; then
    echo 'sys-boot/grub grub_platforms_pc' >> /etc/portage/package.use/grub  # bios support for bios systems
fi

echo 'sys-apps/iproute2 -iptables' >> /etc/portage/package.use/iproute2
echo 'sys-apps/systemd gnuefi' >> /etc/portage/package.use/systemd
echo 'net-nds/openldap sasl' >> /etc/portage/package.use/openldap
echo '>=sys-auth/ssh-ldap-pubkey-1.4.0::gentoo schema' >> /etc/portage/package.use/openldap
echo 'net-mail/dovecot mysql sieve' >> /etc/portage/package.use/dovecot
echo 'mail-filter/opendkim opendbx' >> /etc/portage/package.use/opendkim
echo 'mail-mta/postfix dovecot-sasl mysql sasl' >> /etc/portage/package.use/postfix
echo 'www-servers/nginx rtmp' >> /etc/portage/package.use/nginx
echo '>=app-misc/mime-types-2.1.53::gentoo nginx' >> /etc/portage/package.use/nginx
echo 'dev-vcs/git cgi' >> /etc/portage/package.use/git
echo '>=media-libs/gd-2.3.2-r1 webp' >> /etc/portage/package.use/ejabberd
echo '>=net-im/ejabberd-21.12-r1 mysql' >> /etc/portage/package.use/ejabberd
echo '>=sys-libs/db-5.3.28-r9::gentoo cxx' >> /etc/portage/package.use/murmur

echo '>=dev-python/pipenv-2022.12.19::gentoo ~amd64' >> /etc/portage/package.accept_keywords/dev-python

# musl only valid for amd64 for now
if [[ "${GENTOO_PROFILE}" == *"musl"* ]]; then
    echo "dev-vcs/git -gpg" >> /etc/portage/package.use/musl  # gpg doesn't build on musl profiles
    echo "sys-libs/pam cracklib" >> /etc/portage/package.use/musl
fi
