#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# set profile symlink to the hardcoded PORDIR
ln -sf ../.."${PORTDIR}/profiles/${GENTOO_PROFILE}" /etc/portage/make.profile

# Set timezone
echo 'UTC' > /etc/timezone

if [[ "${GENTOO_PROFILE}" != *"musl"* ]]; then
    # Set locale
    echo 'en_GB.UTF-8 UTF-8' >> /etc/locale.gen
    locale-gen -q
    eselect locale set en_GB.utf8
fi
